### ISSUE TITLE
Ringside Buglist Meta-issue

### ISSUE THREAD

**Issue by ThatJoeMoore** [byuweb/byu-theme-components#367]
Here are the bugs I've discovered so far.  I'm too lazy to create an issue for each of them.

- [x] Footer image is a bitmap wrapped in an SVG, not a true SVG.
- [x] Fallback styles for header don't respect the `constrain-top-bar` and `full-width` attributes.
- [x] Fallback styles don't account for mobile (should use a default breakpoint)

**Comment by blakemorgan** [comment]
Fixed footer bitmap in e1e05435304fe8eb19d492a8c115f2530ba098a4

**Comment by rburkey87** [comment]
I'm on the FOUC issues. Thank you!

**Comment by kebowdog** [comment]
Addressed in #376
